export const GET_VIDEOGAMES = "GET_VIDEOGAMES";
export const GET_ID_VIDEOGAME = "GET_ID_VIDEOGAME";
export const FILTER_VIDEOGAMES = "FILTER_VIDEOGAMES";
export const ORDER_VIDEOGAMES = "ORDER_VIDEOGAMES";