export const GET_VIDEOGAMES = "GET_VIDEOGAMES";
export const GET_ID_VIDEOGAME = "GET_ID_VIDEOGAME";
export const FILTER_BY_GENRE = "FILTER_BY_GENRE";
export const FILTER_BY_CREATED = "FILTER_BY_CREATED";
export const GET_ALL_GENRES = "GET_ALL_GENRES"
export const ORDER_AZ = "ORDER_AZ";
export const ORDER_RATING = "ORDER_RATING";
export const POST_VIDEOGAMES = "POST_VIDEOGAMES";